"use client";

import { FormEvent, useMemo, useState } from "react";
// import { LogoutButton } from "@/components/logout-button";
import { InstallAppButton } from "@/components/install-app-button";
import type { InventoryItem, InventoryItemInput } from "@/lib/inventory-types";

type Status = "In stock" | "Low stock" | "Out of stock";
type Sort = "updated" | "name" | "quantity";
const emptyDraft: InventoryItemInput = { name: "", sku: "", location: "", quantity: 0 };
const statusClass: Record<Status, string> = { "In stock": "bg-emerald-50 text-emerald-700 ring-emerald-600/20 dark:bg-emerald-500/10 dark:text-emerald-300", "Low stock": "bg-amber-50 text-amber-700 ring-amber-600/20 dark:bg-amber-500/10 dark:text-amber-300", "Out of stock": "bg-rose-50 text-rose-700 ring-rose-600/20 dark:bg-rose-500/10 dark:text-rose-300" };
function itemStatus(quantity: number): Status { return quantity === 0 ? "Out of stock" : quantity <= 10 ? "Low stock" : "In stock"; }

export function ItemManagerDashboard({ email, initialItems }: { email?: string; initialItems: InventoryItem[] }) {
  const [items, setItems] = useState(initialItems);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"All" | Status>("All"); const [sort, setSort] = useState<Sort>("updated");
  const [editing, setEditing] = useState<InventoryItem | null>(null); const [adding, setAdding] = useState(false); const [draft, setDraft] = useState<InventoryItemInput>(emptyDraft); const [error, setError] = useState(""); const [pending, setPending] = useState(false);
  const visibleItems = useMemo(() => { const normalizedQuery = query.trim().toLowerCase(); return items.filter((item) => (filter === "All" || itemStatus(item.quantity) === filter) && (!normalizedQuery || [item.name, item.sku, item.location].some((value) => value.toLowerCase().includes(normalizedQuery)))).sort((a, b) => sort === "name" ? a.name.localeCompare(b.name) : sort === "quantity" ? b.quantity - a.quantity : b.updatedAt.localeCompare(a.updatedAt)); }, [filter, items, query, sort]);
  const totalQuantity = items.reduce((total, item) => total + item.quantity, 0); const inStock = items.filter((item) => itemStatus(item.quantity) === "In stock").length; const lowStock = items.filter((item) => itemStatus(item.quantity) === "Low stock").length; const outOfStock = items.filter((item) => itemStatus(item.quantity) === "Out of stock").length;
  function openAdd() { setDraft(emptyDraft); setEditing(null); setError(""); setAdding(true); }
  function openEdit(item: InventoryItem) { setDraft({ name: item.name, sku: item.sku, location: item.location, quantity: item.quantity }); setEditing(item); setError(""); setAdding(true); }
  function closeEditor() { if (!pending) { setAdding(false); setEditing(null); setError(""); } }
  async function saveItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const response = await fetch(editing ? `/api/items/${editing.id}` : "/api/items", { method: editing ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const data = await response.json() as { item?: InventoryItem; error?: string }; if (!response.ok || !data.item) { setError(data.error ?? "Could not save this item."); setPending(false); return; } setItems((current) => editing ? current.map((item) => item.id === data.item!.id ? data.item! : item) : [data.item!, ...current]); setAdding(false); setEditing(null); setPending(false); }
  async function removeItem(item: InventoryItem) { if (!window.confirm(`Delete “${item.name}”? This cannot be undone.`)) return; setError(""); const response = await fetch(`/api/items/${item.id}`, { method: "DELETE" }); if (response.ok) setItems((current) => current.filter((entry) => entry.id !== item.id)); else setError("Could not delete this item. Please try again."); }
  return <div className="min-h-full bg-[#f7f8f6] text-zinc-900 dark:bg-[#09110f] dark:text-zinc-50"><header className="border-b border-zinc-200 bg-white/95 dark:border-zinc-800 dark:bg-[#0c1614]/95"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between gap-4 px-5 sm:px-8"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-brand text-sm font-bold text-white">IM</span><div><p className="text-sm font-bold tracking-wide">POTUSANA’S ITEM MANAGER</p><p className="text-xs text-zinc-500 dark:text-zinc-400">Workspace inventory</p></div></div><div className="flex items-center gap-3"><InstallAppButton />{email ? <p className="hidden text-sm text-zinc-500 sm:block">{email}</p> : null}{/* <LogoutButton className="h-9 rounded-lg border border-zinc-200 px-3 text-sm font-semibold text-zinc-700 hover:bg-zinc-50 dark:border-zinc-700 dark:text-zinc-200 dark:hover:bg-white/5" /> */}</div></div></header>
    <main className="mx-auto w-full max-w-7xl px-5 py-8 sm:px-8 sm:py-10"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand">Inventory overview</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Manage your stock.</h1><p className="mt-2 text-sm text-zinc-600 dark:text-zinc-400">Add, edit, and track stock in this workspace.</p></div><button type="button" onClick={openAdd} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-ink px-4 text-sm font-semibold text-white transition hover:bg-zinc-800 dark:bg-brand dark:text-ink"><span className="text-lg leading-none">+</span> Add item</button></div>
      <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Catalog items" value={String(items.length)} detail={`${totalQuantity} units on hand`} /><StatCard label="In stock" value={String(inStock)} detail="More than 10 units" accent="text-emerald-600 dark:text-emerald-400" /><StatCard label="Low stock" value={String(lowStock)} detail="10 units or fewer" accent="text-amber-600 dark:text-amber-400" /><StatCard label="Out of stock" value={String(outOfStock)} detail="Needs immediate action" accent="text-rose-600 dark:text-rose-400" /></section>
      <section className="mt-8 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-800 dark:bg-[#0c1614]"><div className="flex flex-col gap-4 border-b border-zinc-200 p-5 dark:border-zinc-800 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="font-semibold">Inventory items</h2><p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">{visibleItems.length} item{visibleItems.length === 1 ? "" : "s"} shown</p></div><div className="grid gap-3 sm:grid-cols-3"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search inventory" aria-label="Search inventory" className="h-10 rounded-lg border border-zinc-300 bg-white px-3 text-sm outline-none focus:border-brand dark:border-zinc-700 dark:bg-zinc-950" /><select value={filter} onChange={(event) => setFilter(event.target.value as typeof filter)} aria-label="Filter by stock status" className="h-10 rounded-lg border border-zinc-300 bg-white px-3 text-sm outline-none focus:border-brand dark:border-zinc-700 dark:bg-zinc-950"><option>All</option><option>In stock</option><option>Low stock</option><option>Out of stock</option></select><select value={sort} onChange={(event) => setSort(event.target.value as Sort)} aria-label="Sort inventory" className="h-10 rounded-lg border border-zinc-300 bg-white px-3 text-sm outline-none focus:border-brand dark:border-zinc-700 dark:bg-zinc-950"><option value="updated">Recently updated</option><option value="name">Name A–Z</option><option value="quantity">Most quantity</option></select></div></div>
        {error ? <p role="alert" className="mx-5 mt-5 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700 dark:bg-red-950/50 dark:text-red-300">{error}</p> : null}<div className="divide-y divide-zinc-100 sm:hidden dark:divide-zinc-800">{visibleItems.map((item) => <article key={item.id} className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{item.name}</p><p className="mt-1 font-mono text-xs text-zinc-500">{item.sku || "No SKU"}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass[itemStatus(item.quantity)]}`}>{itemStatus(item.quantity)}</span></div><p className="mt-3 text-sm text-zinc-600 dark:text-zinc-300">{item.location || "No location"} · <strong>{item.quantity}</strong> on hand</p><div className="mt-4 flex gap-4"><button type="button" onClick={() => openEdit(item)} className="font-semibold text-brand">Edit</button><button type="button" onClick={() => removeItem(item)} className="font-semibold text-rose-600">Delete</button></div></article>)}</div><div className="hidden overflow-x-auto sm:block"><table className="min-w-full text-left text-sm"><thead className="bg-zinc-50 text-xs uppercase tracking-wide text-zinc-500 dark:bg-white/5 dark:text-zinc-400"><tr><th className="px-5 py-3 font-medium">Item</th><th className="px-5 py-3 font-medium">Location</th><th className="px-5 py-3 font-medium">On hand</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 font-medium">Updated</th><th className="px-5 py-3"><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-zinc-100 dark:divide-zinc-800">{visibleItems.map((item) => <ItemRow key={item.id} item={item} onEdit={openEdit} onDelete={removeItem} />)}</tbody></table></div>{visibleItems.length === 0 ? <div className="p-12 text-center"><p className="font-semibold">No items found</p><p className="mt-2 text-sm text-zinc-500">Add your first item or change the search and filters.</p><button type="button" onClick={openAdd} className="mt-4 font-semibold text-brand">Add an item</button></div> : null}</section>
    </main>{adding ? <ItemEditor draft={draft} setDraft={setDraft} editing={editing} error={error} pending={pending} onSave={saveItem} onClose={closeEditor} /> : null}</div>;
}
function ItemRow({ item, onEdit, onDelete }: { item: InventoryItem; onEdit: (item: InventoryItem) => void; onDelete: (item: InventoryItem) => void }) { const status = itemStatus(item.quantity); return <tr className="transition hover:bg-zinc-50/80 dark:hover:bg-white/[0.03]"><td className="px-5 py-4"><p className="font-semibold">{item.name}</p><p className="mt-0.5 font-mono text-xs text-zinc-500">{item.sku || "No SKU"}</p></td><td className="px-5 py-4 text-zinc-600 dark:text-zinc-300">{item.location || "No location"}</td><td className="px-5 py-4 font-semibold">{item.quantity}</td><td className="px-5 py-4"><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ring-inset ${statusClass[status]}`}>{status}</span></td><td className="px-5 py-4 whitespace-nowrap text-zinc-500">{new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(item.updatedAt))}</td><td className="px-5 py-4 text-right whitespace-nowrap"><button type="button" onClick={() => onEdit(item)} className="font-semibold text-brand">Edit</button><button type="button" onClick={() => onDelete(item)} className="ml-4 font-semibold text-rose-600">Delete</button></td></tr>; }
function StatCard({ label, value, detail, accent = "" }: { label: string; value: string; detail: string; accent?: string }) { return <article className="rounded-2xl border border-zinc-200 bg-white p-5 shadow-sm dark:border-zinc-800 dark:bg-[#0c1614]"><p className="text-sm font-medium text-zinc-500 dark:text-zinc-400">{label}</p><p className={`mt-3 text-3xl font-semibold tracking-tight ${accent}`}>{value}</p><p className="mt-1 text-sm text-zinc-500 dark:text-zinc-400">{detail}</p></article>; }
function ItemEditor({ draft, setDraft, editing, error, pending, onSave, onClose }: { draft: InventoryItemInput; setDraft: (draft: InventoryItemInput) => void; editing: InventoryItem | null; error: string; pending: boolean; onSave: (event: FormEvent<HTMLFormElement>) => void; onClose: () => void }) { const update = <K extends keyof InventoryItemInput>(key: K, value: InventoryItemInput[K]) => setDraft({ ...draft, [key]: value }); return <div className="fixed inset-0 z-20 flex items-end bg-black/40 sm:items-center sm:justify-center sm:p-5" role="dialog" aria-modal="true"><form onSubmit={onSave} className="w-full max-w-lg rounded-t-2xl bg-white p-6 shadow-xl dark:bg-zinc-950 sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{editing ? "Edit item" : "Add item"}</h2><p className="mt-1 text-sm text-zinc-500">Enter the essentials for this inventory item.</p></div><button type="button" onClick={onClose} className="text-2xl leading-none text-zinc-400" aria-label="Close">×</button></div><div className="mt-6 grid gap-4"><Field label="Item name" value={draft.name} onChange={(value) => update("name", value)} required /><Field label="SKU" value={draft.sku} onChange={(value) => update("sku", value)} /><Field label="Location" value={draft.location} onChange={(value) => update("location", value)} /><label className="grid gap-1.5 text-sm font-medium">Quantity<input type="number" min="0" step="1" required value={draft.quantity} onChange={(event) => update("quantity", Number(event.target.value))} className="h-11 rounded-lg border border-zinc-300 bg-white px-3 font-normal outline-none focus:border-brand dark:border-zinc-700 dark:bg-zinc-900" /></label></div>{error ? <p role="alert" className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p> : null}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={pending} className="h-10 rounded-lg px-4 text-sm font-semibold text-zinc-600">Cancel</button><button type="submit" disabled={pending} className="h-10 rounded-lg bg-ink px-4 text-sm font-semibold text-white disabled:opacity-70 dark:bg-brand dark:text-ink">{pending ? "Saving…" : editing ? "Save changes" : "Add item"}</button></div></form></div>; }
function Field({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} className="h-11 rounded-lg border border-zinc-300 bg-white px-3 font-normal outline-none focus:border-brand dark:border-zinc-700 dark:bg-zinc-900" /></label>; }
